# Generated by Django 5.1.7 on 2025-03-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
